version: "3.7"

services:
  app:
    build:
      context: .
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      MONGO_CONNECTION_STRING: mongodb://root:password@mongo:27017/user

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user